### ISSUE TITLE
Error when running in Terminal

### ISSUE THREAD

**Issue by blnalex** [AndreasBackx/spotifatius#1]
Hello,

when I try to run spotifatius the first time in the terminal I get this error msg:

Error: Could not find RSPOTIFY_CLIENT_(ID|SECRET) environment variables

I followed the instruction, running on Endeavour OS/ Swaywm

Thank you!

**Comment by EysseW** [comment]
Same here. Arch BTW.

**Comment by AndreasBackx** [comment]
Sorry for the late reply, missed this for some reason. You'll want to follow the guide from the Spotify developer page on how to create an application: https://developer.spotify.com/documentation/general/guides/authorization/app-settings/. The redirect URI should be `http://localhost`. I'll update the README to include this information this week hopefully.

**Comment by AndreasBackx** [comment]
Let me know if you have any more questions! Apologies for this taking a while.

**Comment by LoneWolf4713** [comment]
hey @AndreasBackx same issue, here:
```
❯ set -g RSPOTIFY_CLIENT_ID ********************

❯ set -g RSPOTIFY_CLIENT_SECRET ***********************

❯ spotifatius monitor
Error: Could not find RSPOTIFY_CLIENT_(ID|SECRET) environment variables

# I though maybe my fish shell is the problem, so I tried bash, but nah -> 
❯ bash
[prtyksh@neo ~]$ RSPOTIFY_CLIENT_ID=********************
[prtyksh@neo~]$ RSPOTIFY_CLIENT_SECRET=********************

[prtyksh@neo~]$ spotifatius monitor
Error: Could not find RSPOTIFY_CLIENT_(ID|SECRET) environment variables
```
also, wanted to ask if this works on constant polling or like it gets updated when a song changes

**Comment by AndreasBackx** [comment]
@LoneWolf4713 I'm not sure what to tell you. How did you install `spotifatius` and what version is it (`spotifatius --version`)? I would recommend you maybe try to do some debugging yourself with the code. The error is from here: https://github.com/AndreasBackx/spotifatius/blob/main/src/server/liked_tracker.rs#L44-L46. This calls this piece of code: https://docs.rs/rspotify/latest/src/rspotify/lib.rs.html#390-400. It should only error if the variable is not present or if it's not unicode: https://doc.rust-lang.org/std/env/enum.VarError.html. My guess is that there is _something_ in your config that makes it either not pass the value, or there's a non-unicode character in there? Both would surprise me however.

Could you possibly see if `RUST_LOG=trace spotifatius monitor` gives any more information? You may want to try running it directly with the variables in front of it to be extra sure nothing else is messing with it. Though again, it would surprise me.

If this reveals nothing, I'm afraid I don't have the time to debug this for you.

**Comment by LoneWolf4713** [comment]
@AndreasBackx thank you, but nevermind then, im on spotifatius 0.2.5 but I'm afraid I couldn't debug this out either, so nevermind! Thank you for the quick response btw.

**Comment by AndreasBackx** [comment]
@LoneWolf4713 my apologies that I cannot help you further then. Let me know if you somehow do resolve it.

**Comment by shvedes** [comment]
> RSPOTIFY_CLIENT_ID=********************

As far as i know, you need to `export` environment variables to use them in external apps
