### ISSUE TITLE
Error: Could not connect to monitor instance, make sure there is one running

### ISSUE THREAD

**Issue by celsomiranda** [AndreasBackx/spotifatius#2]
I can't seem to get this to work.

Using `monitor` I get no info, just : `{"text":""}`

If I use `toggle-liked` I get:

```
Error: Could not connect to monitor instance, make sure there is one running

Caused by:
    0: transport error
    1: error trying to connect: tcp connect error: Connection refused (os error 111)
    2: tcp connect error: Connection refused (os error 111)
    3: Connection refused (os error 111)
```

**Comment by AndreasBackx** [comment]
You need to have a `spotifatius monitor` running somewhere. This spawns a server, I've updated the documentation to explain this a bit. You want to add this to your bar of choice, currently only Waybar and Polybar are supported. It's not possible right now to use `spotifatius` without running the monitor command somewhere in a bar.

Let me know if you have any more questions.
